### ISSUE TITLE
Unit testing for the runtime libraries

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#468]
We're in the process of reviewing, and unit testing, the HILTI and Spicy runtime libraries. This ticket tracks which pieces are covered so far:

`hilti-rt-tests`:

- [x] hilti/backtrace.h (#475)
- [x] hilti/compiler-setup.h (probably neither worth nor really possible to test)
- [x] hilti/configuration.h (#475)
- [x] hilti/context.h (#478)
- [x] hilti/debug-logger.h (#475)
- [x] hilti/deferred-expression.h (#478)
- [x] hilti/exception.h (#478)
- [X] hilti/extension-points.h (tested in concrete implementations)
- [ ] hilti/fiber.h (staying with old tests for now; may swap out fiber implementation later and may revisit tests then as well)
- [x] hilti/fmt.h (#480)
- [x] hilti/global-state.h (#480)
- [x] hilti/hilti.h (#480 )
- [x] hilti/init.h (#480)
- [x] hilti/iterator.h (needs a pass removing unused functionality, possibly not needed anymore)  (#475)
- [x] hilti/library.h (#478)
- [x] hilti/logging.h (#480)
- [X] hilti/result.h
- [x] hilti/safe-int.h (#475)
- [x] hilti/threading.h (provides only variables, hard to test)
- [X] hilti/type-info.h (NOTE: not unit tested, hardly any incidental coverage)
- [X] hilti/types/address.h
- [X] hilti/types/any.h
- [X] hilti/types/bool.h
- [X] hilti/types/bytes.h
- [X] hilti/types/error.h
- [X] hilti/types/function.h
- [x] hilti/types/integer.h
- [X] hilti/types/interval.h
- [X] hilti/types/map.h
- [x] hilti/types/network.h
- [X] hilti/types/null.h
- [X] hilti/types/optional.h
- [X] hilti/types/port.h
- [X] hilti/types/real.h
- [x] hilti/types/reference.h (#474)
- [X] hilti/types/regexp.h
- [X] hilti/types/result.h
- [X] hilti/types/set.h
- [X] hilti/types/set_fwd.h
- [X] hilti/types/stream.h
- [x] hilti/types/string.h
- [x] hilti/types/struct.h
- [x] hilti/types/time.h
- [X] hilti/types/tuple.h
- [x] hilti/types/union.h
- [X] hilti/types/vector.h
- [X] hilti/types/vector_fwd.h
- [X] hilti/unpack.h
- [X] hilti/util.h (NOTE: file looks unneeded)

`spicy-rt-tests` (needs to be created):

- [x] spicy/base64.h (#484)
- [x] spicy/debug.h (#484)
- [x] spicy/global-state.h (#488)
- [x] spicy/util.h (#488)
- [x] spicy/mime.h (#488)
- [x] spicy/parsed-unit.h (#488)
- [x] spicy/zlib.h (#488)
- [x] spicy/parser.h (#489)
- [x] spicy/init.h (#489)
- [x] ~spicy/sink.h~ (probably not directly intended for users, BTests exercising this might be good enough)
- [x] ~spicy/filter.h~ (probably not directly intended for users, BTests exercising this might be good enough)
- [x] ~spicy/driver.h~ (probably not directly intended for users, BTests exercising this might be good enough)
- [x] ~spicy/spicy.h~
- [x] ~spicy/typedefs.h~

**Comment by rsmmr** [comment]
All done, great work @bbannier!
