### ISSUE TITLE
Release preparation

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#855]
Pulling out todos from the doc updates in #851:

- [x] Rename master artifacts from `spicy.{rpm,deb,tar.gz}` to `spicy-dev.{rpm,deb,tar.gz}` (we already have the release naming `spicy-x.y.z.{rpm,deb,tar.gz}` in place, right?) (see #857)
- [x] Fix the TAR links; the artifacts don't seem to exist. They used to be listed at a different address as the other artifacts as well (including `build` vs not), should unify. (see #857)
- [x] ~Add a 2nd Homebrew formula `spicy-dev` that install from master; change `spicy` to pull from release~
- [x] Create two Dockerhub image `spicy-dev` for nightly builds; let `spicy` use  release. `latest` should point to most recent in either. (see #858)
- [x] Unify Dockerfiles to install the same Zeek version by default (4.0 if possible); set other versions through Cirrus config.

If some of this needs to wait until we actually have a release, that's fine; just recording here what the docs are about to say.

I also started a release check list here to record steps that need to be done manually: https://github.com/zeek/spicy/wiki/Release-Checklist

**Comment by bbannier** [comment]
I believe _Unify Dockerfiles to install the same Zeek version by default_ is done as all images are already at zeek-4.0.0 by default (true for both images in in `docker/` and in `ci/`). The only exception is debian-9 which is still using zeek-3.2.2 since there are no upstream Zeek packages available for that distribution (I believe related to debian-9 not including a recent enough compiler).

**Comment by bbannier** [comment]
Closing this as all listed tasks are either done or not needed anymore.
